language: python
python:
    - 3.3
    - 3.4
matrix:
    allow_failures:
        - python: 3.3
install:
    - "pip install -U pip"
    - "pip install pytest_asyncio"
    - "pip install -e ."
script: "python setup.py test"
